# Generated by Django 3.2.8 on 2021-10-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('user', 'follow_user')},
        ),
    ]
